// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"time"
)

type Channel struct {
	ID             int64
	ChannelPoint   string
	ShortChannelID sql.NullInt64
	PeerID         int64
}

type ChannelEvent struct {
	ID               int64
	ChannelID        int64
	EventType        string
	Timestamp        time.Time
	LocalBalanceSat  sql.NullInt64
	RemoteBalanceSat sql.NullInt64
}

type Peer struct {
	ID     int64
	Pubkey string
	Alias  sql.NullString
}
