// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: peers.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getChannelByChanPoint = `-- name: GetChannelByChanPoint :one
SELECT id, channel_point, short_channel_id, peer_id FROM channels WHERE channel_point = $1
`

func (q *Queries) GetChannelByChanPoint(ctx context.Context, channelPoint string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannelByChanPoint, channelPoint)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ChannelPoint,
		&i.ShortChannelID,
		&i.PeerID,
	)
	return i, err
}

const getChannelByShortChanID = `-- name: GetChannelByShortChanID :one
SELECT id, channel_point, short_channel_id, peer_id FROM channels WHERE short_channel_id = $1
`

func (q *Queries) GetChannelByShortChanID(ctx context.Context, shortChannelID sql.NullInt64) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannelByShortChanID, shortChannelID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.ChannelPoint,
		&i.ShortChannelID,
		&i.PeerID,
	)
	return i, err
}

const getChannelEvents = `-- name: GetChannelEvents :many
SELECT id, channel_id, event_type, timestamp, local_balance_sat, remote_balance_sat FROM channel_events
WHERE channel_id = $1 AND timestamp BETWEEN $2 AND $3
ORDER BY timestamp ASC
`

type GetChannelEventsParams struct {
	ChannelID   int64
	Timestamp   time.Time
	Timestamp_2 time.Time
}

func (q *Queries) GetChannelEvents(ctx context.Context, arg GetChannelEventsParams) ([]ChannelEvent, error) {
	rows, err := q.db.QueryContext(ctx, getChannelEvents, arg.ChannelID, arg.Timestamp, arg.Timestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelEvent
	for rows.Next() {
		var i ChannelEvent
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.EventType,
			&i.Timestamp,
			&i.LocalBalanceSat,
			&i.RemoteBalanceSat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeerByPubKey = `-- name: GetPeerByPubKey :one
SELECT id, pubkey, alias FROM peers WHERE pubkey = $1
`

func (q *Queries) GetPeerByPubKey(ctx context.Context, pubkey string) (Peer, error) {
	row := q.db.QueryRowContext(ctx, getPeerByPubKey, pubkey)
	var i Peer
	err := row.Scan(&i.ID, &i.Pubkey, &i.Alias)
	return i, err
}

const insertChannel = `-- name: InsertChannel :one
INSERT INTO channels (channel_point, short_channel_id, peer_id) VALUES ($1, $2, $3) RETURNING id
`

type InsertChannelParams struct {
	ChannelPoint   string
	ShortChannelID sql.NullInt64
	PeerID         int64
}

func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertChannel, arg.ChannelPoint, arg.ShortChannelID, arg.PeerID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertChannelEvent = `-- name: InsertChannelEvent :exec
INSERT INTO channel_events (
    channel_id, event_type, timestamp, local_balance_sat, remote_balance_sat
) VALUES ($1, $2, $3, $4, $5)
`

type InsertChannelEventParams struct {
	ChannelID        int64
	EventType        string
	Timestamp        time.Time
	LocalBalanceSat  sql.NullInt64
	RemoteBalanceSat sql.NullInt64
}

func (q *Queries) InsertChannelEvent(ctx context.Context, arg InsertChannelEventParams) error {
	_, err := q.db.ExecContext(ctx, insertChannelEvent,
		arg.ChannelID,
		arg.EventType,
		arg.Timestamp,
		arg.LocalBalanceSat,
		arg.RemoteBalanceSat,
	)
	return err
}

const updateShortChanID = `-- name: UpdateShortChanID :exec
UPDATE channels SET short_channel_id = $1 WHERE id = $2
`

type UpdateShortChanIDParams struct {
	ShortChannelID sql.NullInt64
	ID             int64
}

func (q *Queries) UpdateShortChanID(ctx context.Context, arg UpdateShortChanIDParams) error {
	_, err := q.db.ExecContext(ctx, updateShortChanID, arg.ShortChannelID, arg.ID)
	return err
}

const upsertPeer = `-- name: UpsertPeer :one
INSERT INTO peers (pubkey, alias) VALUES ($1, $2)
ON CONFLICT (pubkey) DO UPDATE SET alias = EXCLUDED.alias
RETURNING id
`

type UpsertPeerParams struct {
	Pubkey string
	Alias  sql.NullString
}

func (q *Queries) UpsertPeer(ctx context.Context, arg UpsertPeerParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertPeer, arg.Pubkey, arg.Alias)
	var id int64
	err := row.Scan(&id)
	return id, err
}
