// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetChannelByChanPoint(ctx context.Context, channelPoint string) (Channel, error)
	GetChannelByShortChanID(ctx context.Context, shortChannelID sql.NullInt64) (Channel, error)
	GetChannelEvents(ctx context.Context, arg GetChannelEventsParams) ([]ChannelEvent, error)
	GetPeerByPubKey(ctx context.Context, pubkey string) (Peer, error)
	InsertChannel(ctx context.Context, arg InsertChannelParams) (int64, error)
	InsertChannelEvent(ctx context.Context, arg InsertChannelEventParams) error
	UpdateShortChanID(ctx context.Context, arg UpdateShortChanIDParams) error
	UpsertPeer(ctx context.Context, arg UpsertPeerParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
